// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test1

#ifndef _TEST1_UI_H
#define _TEST1_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#if defined __has_include
#if __has_include("lvgl.h")
#include "lvgl.h"
#elif __has_include("lvgl/lvgl.h")
#include "lvgl/lvgl.h"
#else
#include "lvgl.h"
#endif
#else
#include "lvgl.h"
#endif

#include "ui_helpers.h"
#include "ui_events.h"

// SCREEN: ui_roomdata
void ui_roomdata_screen_init(void);
extern lv_obj_t * ui_roomdata;
extern lv_obj_t * ui_Header;
extern lv_obj_t * ui_Time;
extern lv_obj_t * ui_Date;
extern lv_obj_t * ui_Week;
extern lv_obj_t * ui_Room;
extern lv_obj_t * ui_RTemp;
void ui_event_Arc5(lv_event_t * e);
extern lv_obj_t * ui_Arc5;
extern lv_obj_t * ui_RTemp_Bg;
extern lv_obj_t * ui_RTemp_Num_Bg;
extern lv_obj_t * ui_Label_RTemp;
extern lv_obj_t * ui_RHumid;
void ui_event_Arc2(lv_event_t * e);
extern lv_obj_t * ui_Arc2;
extern lv_obj_t * ui_RHumid_Bg;
extern lv_obj_t * ui_RHumid_Num_Bg;
extern lv_obj_t * ui_Label_RHumid;
extern lv_obj_t * ui_Panel7;
extern lv_obj_t * ui_Switch3;
extern lv_obj_t * ui_LightState;
extern lv_obj_t * ui_LightLevel;
void ui_event_goweather2(lv_event_t * e);
extern lv_obj_t * ui_goweather2;
void ui_event_goroomdoor(lv_event_t * e);
extern lv_obj_t * ui_goroomdoor;
// CUSTOM VARIABLES

// SCREEN: ui_weather
void ui_weather_screen_init(void);
extern lv_obj_t * ui_weather;
extern lv_obj_t * ui_Header1;
extern lv_obj_t * ui_Time1;
extern lv_obj_t * ui_Date1;
extern lv_obj_t * ui_Week1;
extern lv_obj_t * ui_Label13;
extern lv_obj_t * ui_Panel8;
extern lv_obj_t * ui_Panel9;
void ui_event_Slider2(lv_event_t * e);
extern lv_obj_t * ui_Slider2;
extern lv_obj_t * ui_Label_Temp;
extern lv_obj_t * ui_Label_TempS;
extern lv_obj_t * ui_Panel1;
extern lv_obj_t * ui_Panel2;
void ui_event_Slider1(lv_event_t * e);
extern lv_obj_t * ui_Slider1;
extern lv_obj_t * ui_Label_Humid;
extern lv_obj_t * ui_Label_HumidS;
extern lv_obj_t * ui_Panel10;
extern lv_obj_t * ui_Label_Weather;
extern lv_obj_t * ui_Label_WeatherS;
void ui_event_goroomdata2(lv_event_t * e);
extern lv_obj_t * ui_goroomdata2;
void ui_event_goroomdoor2(lv_event_t * e);
extern lv_obj_t * ui_goroomdoor2;
// CUSTOM VARIABLES

// SCREEN: ui_roomdoor
void ui_roomdoor_screen_init(void);
extern lv_obj_t * ui_roomdoor;
extern lv_obj_t * ui_Header3;
extern lv_obj_t * ui_Time3;
extern lv_obj_t * ui_Date3;
extern lv_obj_t * ui_Room2;
extern lv_obj_t * ui_Panel4;
extern lv_obj_t * ui_Switch2;
extern lv_obj_t * ui_DoorState;
void ui_event_goroomdata(lv_event_t * e);
extern lv_obj_t * ui_goroomdata;
void ui_event_goweather(lv_event_t * e);
extern lv_obj_t * ui_goweather;
extern lv_obj_t * ui_WhenUNK;
// CUSTOM VARIABLES

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// UI INIT
void ui_init(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
