// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test1

#include "ui.h"

void ui_roomdata_screen_init(void)
{
    ui_roomdata = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_roomdata, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_roomdata, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roomdata, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_roomdata, lv_color_hex(0x28323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header = lv_obj_create(ui_roomdata);
    lv_obj_set_height(ui_Header, 20);
    lv_obj_set_width(ui_Header, lv_pct(100));
    lv_obj_set_align(ui_Header, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Header, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Time, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time, "03:04"); //time
    lv_obj_set_style_text_color(ui_Time, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Date, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date, -6);
    lv_obj_set_y(ui_Date, 0);
    lv_obj_set_align(ui_Date, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Date, "25/11"); //date
    lv_obj_set_style_text_color(ui_Date, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Week = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Week, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Week, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Week, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Week, "Mon"); //week
    lv_obj_add_flag(ui_Week, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Week, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Week, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Room = lv_label_create(ui_Header);
    lv_obj_set_width(ui_Room, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Room, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Room, 135);
    lv_obj_set_y(ui_Room, 0);
    lv_obj_set_align(ui_Room, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Room, "Room");
    lv_obj_set_style_text_color(ui_Room, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Room, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Room, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTemp = lv_obj_create(ui_roomdata);
    lv_obj_set_width(ui_RTemp, 120);
    lv_obj_set_height(ui_RTemp, 142);
    lv_obj_set_x(ui_RTemp, -101);
    lv_obj_set_y(ui_RTemp, 6);
    lv_obj_set_align(ui_RTemp, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RTemp, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RTemp, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc5 = lv_arc_create(ui_RTemp);
    lv_obj_set_width(ui_Arc5, 110);
    lv_obj_set_height(ui_Arc5, 110);
    lv_obj_set_x(ui_Arc5, 0);
    lv_obj_set_y(ui_Arc5, -10);
    lv_obj_set_align(ui_Arc5, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc5, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_range(ui_Arc5, 10, 35);
    lv_arc_set_value(ui_Arc5, 21);
    lv_obj_set_style_radius(ui_Arc5, 350, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Arc5, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Arc5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc5, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc5, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc5, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc5, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc5, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RTemp_Bg = lv_obj_create(ui_RTemp);
    lv_obj_set_width(ui_RTemp_Bg, 60);
    lv_obj_set_height(ui_RTemp_Bg, 60);
    lv_obj_set_x(ui_RTemp_Bg, 0);
    lv_obj_set_y(ui_RTemp_Bg, -11);
    lv_obj_set_align(ui_RTemp_Bg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RTemp_Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RTemp_Bg, 280, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RTemp_Bg, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RTemp_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RTemp_Bg, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RTemp_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RTemp_Bg, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RTemp_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RTemp_Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RTemp_Bg, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RTemp_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RTemp_Bg, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RTemp_Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_RTemp_Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_RTemp_Bg, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RTemp_Num_Bg = lv_obj_create(ui_RTemp_Bg);
    lv_obj_set_width(ui_RTemp_Num_Bg, 45);
    lv_obj_set_height(ui_RTemp_Num_Bg, 45);
    lv_obj_set_align(ui_RTemp_Num_Bg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RTemp_Num_Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RTemp_Num_Bg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RTemp_Num_Bg, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RTemp_Num_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RTemp_Num_Bg, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RTemp_Num_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RTemp_Num_Bg, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RTemp_Num_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RTemp_Num_Bg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_RTemp = lv_label_create(ui_RTemp_Num_Bg);
    lv_obj_set_width(ui_Label_RTemp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_RTemp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_RTemp, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_RTemp, "23°C");
    lv_obj_set_style_text_color(ui_Label_RTemp, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_RTemp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_RTemp, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RHumid = lv_obj_create(ui_roomdata);
    lv_obj_set_width(ui_RHumid, 120);
    lv_obj_set_height(ui_RHumid, 142);
    lv_obj_set_x(ui_RHumid, 97);
    lv_obj_set_y(ui_RHumid, 4);
    lv_obj_set_align(ui_RHumid, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RHumid, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_RHumid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RHumid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RHumid, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Arc2 = lv_arc_create(ui_RHumid);
    lv_obj_set_width(ui_Arc2, 110);
    lv_obj_set_height(ui_Arc2, 110);
    lv_obj_set_x(ui_Arc2, 0);
    lv_obj_set_y(ui_Arc2, -10);
    lv_obj_set_align(ui_Arc2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Arc2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_arc_set_value(ui_Arc2, 69);
    lv_obj_set_style_radius(ui_Arc2, 350, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Arc2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_left(ui_Arc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_right(ui_Arc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_top(ui_Arc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_pad_bottom(ui_Arc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x0F1215), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 10, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_arc_color(ui_Arc2, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_opa(ui_Arc2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_arc_width(ui_Arc2, 10, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Arc2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Arc2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_RHumid_Bg = lv_obj_create(ui_RHumid);
    lv_obj_set_width(ui_RHumid_Bg, 60);
    lv_obj_set_height(ui_RHumid_Bg, 60);
    lv_obj_set_x(ui_RHumid_Bg, 0);
    lv_obj_set_y(ui_RHumid_Bg, -11);
    lv_obj_set_align(ui_RHumid_Bg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RHumid_Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RHumid_Bg, 280, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RHumid_Bg, lv_color_hex(0x646464), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RHumid_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RHumid_Bg, lv_color_hex(0x3C414B), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RHumid_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RHumid_Bg, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RHumid_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RHumid_Bg, 2, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_RHumid_Bg, lv_color_hex(0x050A0F), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_RHumid_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_width(ui_RHumid_Bg, 80, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_spread(ui_RHumid_Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_x(ui_RHumid_Bg, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_ofs_y(ui_RHumid_Bg, 30, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_RHumid_Num_Bg = lv_obj_create(ui_RHumid_Bg);
    lv_obj_set_width(ui_RHumid_Num_Bg, 45);
    lv_obj_set_height(ui_RHumid_Num_Bg, 45);
    lv_obj_set_align(ui_RHumid_Num_Bg, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_RHumid_Num_Bg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_RHumid_Num_Bg, 200, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_RHumid_Num_Bg, lv_color_hex(0x0C191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_RHumid_Num_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_RHumid_Num_Bg, lv_color_hex(0x191C26), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_dir(ui_RHumid_Num_Bg, LV_GRAD_DIR_VER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_RHumid_Num_Bg, lv_color_hex(0x5A646E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_RHumid_Num_Bg, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_RHumid_Num_Bg, 1, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_RHumid = lv_label_create(ui_RHumid_Num_Bg);
    lv_obj_set_width(ui_Label_RHumid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_RHumid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Label_RHumid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_RHumid, "69%");
    lv_obj_set_style_text_color(ui_Label_RHumid, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_RHumid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_RHumid, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel7 = lv_obj_create(ui_roomdata);
    lv_obj_set_width(ui_Panel7, 184);
    lv_obj_set_height(ui_Panel7, 54);
    lv_obj_set_x(ui_Panel7, 1);
    lv_obj_set_y(ui_Panel7, 56);
    lv_obj_set_align(ui_Panel7, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel7, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel7, 10, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel7, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel7, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel7, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch3 = lv_switch_create(ui_Panel7);
    lv_obj_set_width(ui_Switch3, 30);
    lv_obj_set_height(ui_Switch3, 19);
    lv_obj_set_x(ui_Switch3, 38);
    lv_obj_set_y(ui_Switch3, -12);
    lv_obj_set_align(ui_Switch3, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch3, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0xDF5345), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch3, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch3, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_LightState = lv_label_create(ui_Panel7);
    lv_obj_set_width(ui_LightState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LightState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LightState, -31);
    lv_obj_set_y(ui_LightState, -11);
    lv_obj_set_align(ui_LightState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LightState, "Light");
    lv_obj_set_style_text_color(ui_LightState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_LightState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_LightState, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_LightLevel = lv_slider_create(ui_Panel7);
    lv_slider_set_range(ui_LightLevel, 0, 100);
    lv_slider_set_value(ui_LightLevel, 50, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_LightLevel) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_LightLevel, 0, LV_ANIM_OFF);
    lv_obj_set_height(ui_LightLevel, 10);
    lv_obj_set_width(ui_LightLevel, lv_pct(109));
    lv_obj_set_x(ui_LightLevel, 0);
    lv_obj_set_y(ui_LightLevel, 14);
    lv_obj_set_align(ui_LightLevel, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_LightLevel, LV_OBJ_FLAG_CLICKABLE);      /// Flags

    lv_obj_set_style_bg_color(ui_LightLevel, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightLevel, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_LightLevel, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_LightLevel, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_goweather2 = lv_btn_create(ui_roomdata);
    lv_obj_set_width(ui_goweather2, 91);
    lv_obj_set_height(ui_goweather2, lv_pct(100));
    lv_obj_set_x(ui_goweather2, 113);
    lv_obj_set_y(ui_goweather2, -2);
    lv_obj_set_align(ui_goweather2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goweather2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goweather2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goweather2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goweather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_goweather2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_goweather2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goroomdoor = lv_btn_create(ui_roomdata);
    lv_obj_set_width(ui_goroomdoor, 93);
    lv_obj_set_height(ui_goroomdoor, lv_pct(100));
    lv_obj_set_x(ui_goroomdoor, -111);
    lv_obj_set_y(ui_goroomdoor, -3);
    lv_obj_set_align(ui_goroomdoor, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goroomdoor, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goroomdoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goroomdoor, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goroomdoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_goroomdoor, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_goroomdoor, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Arc5, ui_event_Arc5, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Arc2, ui_event_Arc2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goweather2, ui_event_goweather2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goroomdoor, ui_event_goroomdoor, LV_EVENT_ALL, NULL);

}
