// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test1

#include "ui.h"

void ui_weather_screen_init(void)
{
    ui_weather = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_weather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_weather, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_weather, lv_color_hex(0x28323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header1 = lv_obj_create(ui_weather);
    lv_obj_set_height(ui_Header1, 20);
    lv_obj_set_width(ui_Header1, lv_pct(100));
    lv_obj_set_align(ui_Header1, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Header1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header1, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time1 = lv_label_create(ui_Header1);
    lv_obj_set_width(ui_Time1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time1, "03:04");
    lv_obj_set_style_text_color(ui_Time1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date1 = lv_label_create(ui_Header1);
    lv_obj_set_width(ui_Date1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date1, -6);
    lv_obj_set_y(ui_Date1, 0);
    lv_obj_set_align(ui_Date1, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Date1, "25/11");
    lv_obj_set_style_text_color(ui_Date1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Week1 = lv_label_create(ui_Header1);
    lv_obj_set_width(ui_Week1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Week1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Week1, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_Week1, "Mon");
    lv_obj_add_flag(ui_Week1, LV_OBJ_FLAG_HIDDEN);     /// Flags
    lv_obj_set_style_text_color(ui_Week1, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Week1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label13 = lv_label_create(ui_Header1);
    lv_obj_set_width(ui_Label13, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label13, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label13, 134);
    lv_obj_set_y(ui_Label13, 0);
    lv_obj_set_align(ui_Label13, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label13, "Street");
    lv_obj_set_style_text_color(ui_Label13, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label13, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel8 = lv_obj_create(ui_weather);
    lv_obj_set_height(ui_Panel8, 89);
    lv_obj_set_width(ui_Panel8, lv_pct(49));
    lv_obj_set_x(ui_Panel8, 80);
    lv_obj_set_y(ui_Panel8, 38);
    lv_obj_set_align(ui_Panel8, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel8, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel8, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel8, lv_color_hex(0x2E333E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel8, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel8, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel9 = lv_obj_create(ui_Panel8);
    lv_obj_set_height(ui_Panel9, 25);
    lv_obj_set_width(ui_Panel9, lv_pct(116));
    lv_obj_set_x(ui_Panel9, 0);
    lv_obj_set_y(ui_Panel9, -6);
    lv_obj_set_align(ui_Panel9, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel9, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel9, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel9, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel9, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider2 = lv_slider_create(ui_Panel9);
    lv_slider_set_range(ui_Slider2, 10, 35);
    lv_slider_set_value(ui_Slider2, 26, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider2) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider2, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider2, 150);
    lv_obj_set_height(ui_Slider2, 10);
    lv_obj_set_align(ui_Slider2, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider2, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider2, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label_Temp = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label_Temp, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Temp, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Temp, 0);
    lv_obj_set_y(ui_Label_Temp, -8);
    lv_obj_set_align(ui_Label_Temp, LV_ALIGN_TOP_MID);
    lv_label_set_text(ui_Label_Temp, "temp");
    lv_obj_set_style_text_color(ui_Label_Temp, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Temp, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_TempS = lv_label_create(ui_Panel8);
    lv_obj_set_width(ui_Label_TempS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_TempS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_TempS, -1);
    lv_obj_set_y(ui_Label_TempS, 26);
    lv_obj_set_align(ui_Label_TempS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_TempS, "26°C");
    lv_obj_set_style_text_color(ui_Label_TempS, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_TempS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel1 = lv_obj_create(ui_weather);
    lv_obj_set_height(ui_Panel1, 89);
    lv_obj_set_width(ui_Panel1, lv_pct(49));
    lv_obj_set_x(ui_Panel1, -80);
    lv_obj_set_y(ui_Panel1, 38);
    lv_obj_set_align(ui_Panel1, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel1, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel1, lv_color_hex(0x2E333E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel1, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel2 = lv_obj_create(ui_Panel1);
    lv_obj_set_height(ui_Panel2, 25);
    lv_obj_set_width(ui_Panel2, lv_pct(116));
    lv_obj_set_x(ui_Panel2, 0);
    lv_obj_set_y(ui_Panel2, -6);
    lv_obj_set_align(ui_Panel2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel2, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Slider1 = lv_slider_create(ui_Panel2);
    lv_slider_set_value(ui_Slider1, 64, LV_ANIM_OFF);
    if(lv_slider_get_mode(ui_Slider1) == LV_SLIDER_MODE_RANGE) lv_slider_set_left_value(ui_Slider1, 0, LV_ANIM_OFF);
    lv_obj_set_width(ui_Slider1, 150);
    lv_obj_set_height(ui_Slider1, 10);
    lv_obj_set_align(ui_Slider1, LV_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 255, LV_PART_INDICATOR | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Slider1, lv_color_hex(0xFFFFFF), LV_PART_KNOB | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Slider1, 0, LV_PART_KNOB | LV_STATE_DEFAULT);

    ui_Label_Humid = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label_Humid, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Humid, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Humid, -1);
    lv_obj_set_y(ui_Label_Humid, -30);
    lv_obj_set_align(ui_Label_Humid, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Humid, "Humidity");
    lv_obj_set_style_text_color(ui_Label_Humid, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Humid, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_HumidS = lv_label_create(ui_Panel1);
    lv_obj_set_width(ui_Label_HumidS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_HumidS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_HumidS, -1);
    lv_obj_set_y(ui_Label_HumidS, 24);
    lv_obj_set_align(ui_Label_HumidS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_HumidS, "64%");
    lv_obj_set_style_text_color(ui_Label_HumidS, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_HumidS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel10 = lv_obj_create(ui_weather);
    lv_obj_set_height(ui_Panel10, 56);
    lv_obj_set_width(ui_Panel10, lv_pct(99));
    lv_obj_set_x(ui_Panel10, 0);
    lv_obj_set_y(ui_Panel10, -35);
    lv_obj_set_align(ui_Panel10, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel10, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Panel10, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Panel10, lv_color_hex(0x2E333E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel10, lv_color_hex(0x2D323C), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel10, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_Weather = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label_Weather, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_Weather, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_Weather, -97);
    lv_obj_set_y(ui_Label_Weather, 0);
    lv_obj_set_align(ui_Label_Weather, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_Weather, "weather");
    lv_obj_set_style_text_color(ui_Label_Weather, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_Weather, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Label_WeatherS = lv_label_create(ui_Panel10);
    lv_obj_set_width(ui_Label_WeatherS, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label_WeatherS, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label_WeatherS, 53);
    lv_obj_set_y(ui_Label_WeatherS, -1);
    lv_obj_set_align(ui_Label_WeatherS, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label_WeatherS, "weather");
    lv_obj_set_style_text_color(ui_Label_WeatherS, lv_color_hex(0xD7D7D7), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Label_WeatherS, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_Label_WeatherS, &lv_font_montserrat_16, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goroomdata2 = lv_btn_create(ui_weather);
    lv_obj_set_width(ui_goroomdata2, 99);
    lv_obj_set_height(ui_goroomdata2, lv_pct(100));
    lv_obj_set_x(ui_goroomdata2, -107);
    lv_obj_set_y(ui_goroomdata2, -3);
    lv_obj_set_align(ui_goroomdata2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goroomdata2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goroomdata2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goroomdata2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goroomdata2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_goroomdata2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_goroomdata2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goroomdoor2 = lv_btn_create(ui_weather);
    lv_obj_set_width(ui_goroomdoor2, 93);
    lv_obj_set_height(ui_goroomdoor2, lv_pct(100));
    lv_obj_set_x(ui_goroomdoor2, 111);
    lv_obj_set_y(ui_goroomdoor2, -3);
    lv_obj_set_align(ui_goroomdoor2, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goroomdoor2, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goroomdoor2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goroomdoor2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goroomdoor2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_goroomdoor2, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_goroomdoor2, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_Slider2, ui_event_Slider2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_Slider1, ui_event_Slider1, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goroomdata2, ui_event_goroomdata2, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goroomdoor2, ui_event_goroomdoor2, LV_EVENT_ALL, NULL);

}
