// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test1

#include "ui.h"
#include "ui_helpers.h"

///////////////////// VARIABLES ////////////////////


// SCREEN: ui_roomdata
void ui_roomdata_screen_init(void);
lv_obj_t * ui_roomdata;
lv_obj_t * ui_Header;
lv_obj_t * ui_Time;
lv_obj_t * ui_Date;
lv_obj_t * ui_Week;
lv_obj_t * ui_Room;
lv_obj_t * ui_RTemp;
void ui_event_Arc5(lv_event_t * e);
lv_obj_t * ui_Arc5;
lv_obj_t * ui_RTemp_Bg;
lv_obj_t * ui_RTemp_Num_Bg;
lv_obj_t * ui_Label_RTemp;
lv_obj_t * ui_RHumid;
void ui_event_Arc2(lv_event_t * e);
lv_obj_t * ui_Arc2;
lv_obj_t * ui_RHumid_Bg;
lv_obj_t * ui_RHumid_Num_Bg;
lv_obj_t * ui_Label_RHumid;
lv_obj_t * ui_Panel7;
void ui_event_Switch3(lv_event_t * e);
lv_obj_t * ui_Switch3;
lv_obj_t * ui_LightState;
lv_obj_t * ui_LightLevel;
void ui_event_goweather2(lv_event_t * e);
lv_obj_t * ui_goweather2;
void ui_event_goroomdoor(lv_event_t * e);
lv_obj_t * ui_goroomdoor;
// CUSTOM VARIABLES


// SCREEN: ui_weather
void ui_weather_screen_init(void);
lv_obj_t * ui_weather;
lv_obj_t * ui_Header1;
lv_obj_t * ui_Time1;
lv_obj_t * ui_Date1;
lv_obj_t * ui_Week1;
lv_obj_t * ui_Label13;
lv_obj_t * ui_Panel8;
lv_obj_t * ui_Panel9;
void ui_event_Slider2(lv_event_t * e);
lv_obj_t * ui_Slider2;
lv_obj_t * ui_Label_Temp;
lv_obj_t * ui_Label_TempS;
lv_obj_t * ui_Panel1;
lv_obj_t * ui_Panel2;
void ui_event_Slider1(lv_event_t * e);
lv_obj_t * ui_Slider1;
lv_obj_t * ui_Label_Humid;
lv_obj_t * ui_Label_HumidS;
lv_obj_t * ui_Panel10;
lv_obj_t * ui_Label_Weather;
lv_obj_t * ui_Label_WeatherS;
void ui_event_goroomdata2(lv_event_t * e);
lv_obj_t * ui_goroomdata2;
void ui_event_goroomdoor2(lv_event_t * e);
lv_obj_t * ui_goroomdoor2;
// CUSTOM VARIABLES


// SCREEN: ui_roomdoor
void ui_roomdoor_screen_init(void);
lv_obj_t * ui_roomdoor;
lv_obj_t * ui_Header3;
lv_obj_t * ui_Time3;
lv_obj_t * ui_Date3;
lv_obj_t * ui_Room2;
lv_obj_t * ui_Panel4;
lv_obj_t * ui_Switch2;
lv_obj_t * ui_DoorState;
void ui_event_goroomdata(lv_event_t * e);
lv_obj_t * ui_goroomdata;
void ui_event_goweather(lv_event_t * e);
lv_obj_t * ui_goweather;
lv_obj_t * ui_WhenUNK;
// CUSTOM VARIABLES

// EVENTS
lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS

///////////////////// TEST LVGL SETTINGS ////////////////////
#if LV_COLOR_DEPTH != 32
    #error "LV_COLOR_DEPTH should be 32bit to match SquareLine Studio's settings"
#endif
#if LV_COLOR_16_SWAP !=0
    #error "LV_COLOR_16_SWAP should be 0 to match SquareLine Studio's settings"
#endif

///////////////////// ANIMATIONS ////////////////////

///////////////////// FUNCTIONS ////////////////////
void ui_event_Arc5(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label_RTemp, target, "", "°C");
    }
}

void ui_event_Arc2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_Label_RHumid, target, "", "°C");
    }
}

void ui_event_Switch3(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED &&  !lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_LightLevel, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_REMOVE);
    }
    if(event_code == LV_EVENT_VALUE_CHANGED &&  lv_obj_has_state(target, LV_STATE_CHECKED)) {
        _ui_flag_modify(ui_LightLevel, LV_OBJ_FLAG_CLICKABLE, _UI_MODIFY_FLAG_ADD);
    }
}

void ui_event_goweather2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_weather_screen_init);
    }
}

void ui_event_goroomdoor(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_weather_screen_init);
    }
}

void ui_event_Slider2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label_TempS, target, "", "°C");
    }
}

void ui_event_Slider1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_slider_set_text_value(ui_Label_HumidS, target, "", "%");
    }
}

void ui_event_goroomdata2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_roomdata, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_roomdata_screen_init);
    }
}

void ui_event_goroomdoor2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_roomdoor, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_roomdoor_screen_init);
    }
}

void ui_event_goroomdata(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_roomdata, LV_SCR_LOAD_ANIM_MOVE_LEFT, 500, 0, &ui_roomdata_screen_init);
    }
}

void ui_event_goweather(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_weather, LV_SCR_LOAD_ANIM_MOVE_RIGHT, 500, 0, &ui_weather_screen_init);
    }
}

///////////////////// SCREENS ////////////////////

void ui_init(void)
{
    lv_disp_t * dispp = lv_disp_get_default();
    lv_theme_t * theme = lv_theme_default_init(dispp, lv_palette_main(LV_PALETTE_BLUE), lv_palette_main(LV_PALETTE_RED),
                                               false, LV_FONT_DEFAULT);
    lv_disp_set_theme(dispp, theme);
    ui_roomdata_screen_init();
    ui_weather_screen_init();
    ui_roomdoor_screen_init();
    ui____initial_actions0 = lv_obj_create(NULL);
    lv_disp_load_scr(ui_roomdata);
}
