// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.0
// LVGL version: 8.3.11
// Project name: Test1

#include "ui.h"

void ui_roomdoor_screen_init(void)
{
    ui_roomdoor = lv_obj_create(NULL);
    lv_obj_clear_flag(ui_roomdoor, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_roomdoor, lv_color_hex(0x464B55), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_roomdoor, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_grad_color(ui_roomdoor, lv_color_hex(0x28323C), LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Header3 = lv_obj_create(ui_roomdoor);
    lv_obj_set_height(ui_Header3, 20);
    lv_obj_set_width(ui_Header3, lv_pct(100));
    lv_obj_set_align(ui_Header3, LV_ALIGN_TOP_MID);
    lv_obj_clear_flag(ui_Header3, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_color(ui_Header3, lv_color_hex(0x14191E), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Header3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_width(ui_Header3, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Time3 = lv_label_create(ui_Header3);
    lv_obj_set_width(ui_Time3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Time3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_Time3, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Time3, "03:04");
    lv_obj_set_style_text_color(ui_Time3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Time3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Date3 = lv_label_create(ui_Header3);
    lv_obj_set_width(ui_Date3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Date3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Date3, -6);
    lv_obj_set_y(ui_Date3, 0);
    lv_obj_set_align(ui_Date3, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_Date3, "25/11");
    lv_obj_set_style_text_color(ui_Date3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Date3, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Room2 = lv_label_create(ui_Header3);
    lv_obj_set_width(ui_Room2, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Room2, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Room2, 60);
    lv_obj_set_y(ui_Room2, 0);
    lv_obj_set_align(ui_Room2, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Room2, "Room");
    lv_obj_set_style_text_color(ui_Room2, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_Room2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_Room2, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Panel4 = lv_obj_create(ui_roomdoor);
    lv_obj_set_width(ui_Panel4, 137);
    lv_obj_set_height(ui_Panel4, 57);
    lv_obj_set_x(ui_Panel4, 0);
    lv_obj_set_y(ui_Panel4, -100);
    lv_obj_set_align(ui_Panel4, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Panel4, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Panel4, lv_color_hex(0x1E232D), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_color(ui_Panel4, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_border_opa(ui_Panel4, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_Switch2 = lv_switch_create(ui_Panel4);
    lv_obj_set_width(ui_Switch2, 64);
    lv_obj_set_height(ui_Switch2, 36);
    lv_obj_set_x(ui_Switch2, 26);
    lv_obj_set_y(ui_Switch2, 1);
    lv_obj_set_align(ui_Switch2, LV_ALIGN_CENTER);
    lv_obj_clear_flag(ui_Switch2, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0xDF5345), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_set_style_bg_color(ui_Switch2, lv_color_hex(0x36B9F6), LV_PART_INDICATOR | LV_STATE_CHECKED);
    lv_obj_set_style_bg_opa(ui_Switch2, 255, LV_PART_INDICATOR | LV_STATE_CHECKED);

    ui_DoorState = lv_label_create(ui_Panel4);
    lv_obj_set_width(ui_DoorState, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DoorState, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DoorState, -36);
    lv_obj_set_y(ui_DoorState, 0);
    lv_obj_set_align(ui_DoorState, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DoorState, "Door");
    lv_obj_set_style_text_color(ui_DoorState, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_DoorState, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_DoorState, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goroomdata = lv_btn_create(ui_roomdoor);
    lv_obj_set_width(ui_goroomdata, 21);
    lv_obj_set_height(ui_goroomdata, lv_pct(100));
    lv_obj_set_x(ui_goroomdata, 70);
    lv_obj_set_y(ui_goroomdata, -2);
    lv_obj_set_align(ui_goroomdata, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goroomdata, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goroomdata, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goroomdata, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goroomdata, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_goroomdata, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_goroomdata, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_goweather = lv_btn_create(ui_roomdoor);
    lv_obj_set_width(ui_goweather, 23);
    lv_obj_set_height(ui_goweather, lv_pct(100));
    lv_obj_set_x(ui_goweather, -70);
    lv_obj_set_y(ui_goweather, -2);
    lv_obj_set_align(ui_goweather, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_goweather, LV_OBJ_FLAG_SCROLL_ON_FOCUS);     /// Flags
    lv_obj_clear_flag(ui_goweather, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_goweather, lv_color_hex(0xFFFFFF), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_bg_opa(ui_goweather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_color(ui_goweather, lv_color_hex(0x000000), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_shadow_opa(ui_goweather, 0, LV_PART_MAIN | LV_STATE_DEFAULT);

    ui_WhenUNK = lv_label_create(ui_roomdoor);
    lv_obj_set_width(ui_WhenUNK, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WhenUNK, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WhenUNK, 0);
    lv_obj_set_y(ui_WhenUNK, 23);
    lv_obj_set_align(ui_WhenUNK, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WhenUNK, "Mom Deceted\nSTOP Gaming");
    lv_obj_set_style_text_color(ui_WhenUNK, lv_color_hex(0xFF0202), LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(ui_WhenUNK, 255, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(ui_WhenUNK, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(ui_WhenUNK, &lv_font_montserrat_20, LV_PART_MAIN | LV_STATE_DEFAULT);

    lv_obj_add_event_cb(ui_goroomdata, ui_event_goroomdata, LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_goweather, ui_event_goweather, LV_EVENT_ALL, NULL);

}
